<a href="https://colab.research.google.com/github/CE334/CE334_230639_Mayank_Agrawal/blob/main/CE334_MayankAgrawal_230639_Lab_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#Q1
# Using user input method
n = int(input("Enter no. of elements: "))

vals = []   #taking input values
for i in range(n):
    vals.append(int(input("Enter value: ")))

row_vector = [vals]    # row vector size = 1*n
print("row_vector: ")
print(row_vector)

col_vector = []     #column vector of size = n*1
for v in vals:
  col_vector.append([v])
print("col_vector: ")
print(row_vector)


#Using manually
row_v = [[32, 323, 56, 59]]
col_v = [[32], [323], [56], [59]]
print(row_v)
print(col_v)

Enter no. of elements: 3
Enter value: 151
Enter value: 33
Enter value: 23
row_vector: 
[[151, 33, 23]]
col_vector: 
[[151, 33, 23]]
[[32, 323, 56, 59]]
[[32], [323], [56], [59]]


In [35]:
#Q2
import numpy as np

# manually created 5x5 matrix
a = np.array([
    [51, 2, 53, 405, 56],
    [6, 87, 854, 59, 130],
    [165551, 612, 13, 14, 15],
    [166, 17, 158, 19, 20],
    [21, 52, 53, 456, 25]
])

print("Matrix a (manual):")
print(a)

print()
#using input method
val = []
for i in range(5):
  val.append(int(input("enter the value: ")))

row_vect = [val]    #row vector size = 1*5
print("row_vector: ")
print(row_vect)

col_vect = []        #column vector of size = 5*1
for v in vals:
  col_vector.append([v])
print("col_vector: ")
print(row_vect)


Matrix a (manual):
[[ 51   2  53 405  56]
 [  6  87 854  59 130]
 [151 612  13  14  15]
 [166  17 158  19  20]
 [ 21  52  53 456  25]]
enter the value: 313
enter the value: 13
enter the value: 4
enter the value: 1
enter the value: 56
row_vector: 
[[313, 13, 4, 1, 56]]
col_vector: 
[[313, 13, 4, 1, 56]]


In [36]:
#Q3
third_row = a[2,:]    #3rd row extraction
print(third_row)

print()

#Q4
third_column = a[:, 2]     #3rd column extraction
print(third_column)

[151 612  13  14  15]

[ 53 854  13 158  53]


In [37]:
#Q5
row_sort = np.sort(a, axis=1)    #row wise sort
print(row_sort)

print()

col_sort = np.sort(a, axis=0)    #column wise sort6
print(col_sort)

[[  2  51  53  56 405]
 [  6  59  87 130 854]
 [ 13  14  15 151 612]
 [ 17  19  20 158 166]
 [ 21  25  52  53 456]]

[[  6   2  13  14  15]
 [ 21  17  53  19  20]
 [ 51  52  53  59  25]
 [151  87 158 405  56]
 [166 612 854 456 130]]


In [38]:
#Q6
import numpy as np

# creating a copy of matrix a
b = a.copy()

# applying condition using for loop
for i in range(5):
    for j in range(5):
        if b[i][j] > 2:
            b[i][j] = b[i][j] * 10

print("b = ")
print(b)


b = 
[[ 510    2  530 4050  560]
 [  60  870 8540  590 1300]
 [1510 6120  130  140  150]
 [1660  170 1580  190  200]
 [ 210  520  530 4560  250]]


In [39]:
#Q7
print(a + b)

print()

#Q8
print(a-b)

[[ 561    4  583 4455  616]
 [  66  957 9394  649 1430]
 [1661 6732  143  154  165]
 [1826  187 1738  209  220]
 [ 231  572  583 5016  275]]

[[ -459     0  -477 -3645  -504]
 [  -54  -783 -7686  -531 -1170]
 [-1359 -5508  -117  -126  -135]
 [-1494  -153 -1422  -171  -180]
 [ -189  -468  -477 -4104  -225]]


In [40]:
#Q9
import numpy as np

print(a*b)    #using element-wise
print()

d = np.zeros((5, 5))
for i in range(5):
  for j in range(5):
    for k in range(5):
      d[i][j] = d[i][j] + a[i][k]*b[k][j]

print("using matrix multiplication:")
print(d)

[[  26010       4   28090 1640250   31360]
 [    360   75690 7293160   34810  169000]
 [ 228010 3745440    1690    1960    2250]
 [ 275560    2890  249640    3610    4000]
 [   4410   27040   28090 2079360    6250]]

using matrix multiplication:
[[ 790220.  424172.  720580.  547460.  134110.]
 [1423060. 5379812. 1019300.  799200.  288860.]
 [ 159750.  622482. 5338270. 1045510.  888660.]
 [ 360000.  995712.  294320.  799260.  147560.]
 [ 856070.  460162. 1195830.  323790.  184760.]]


In [41]:
#Q10
print(a/18)
print(b/18)

[[ 2.83333333  0.11111111  2.94444444 22.5         3.11111111]
 [ 0.33333333  4.83333333 47.44444444  3.27777778  7.22222222]
 [ 8.38888889 34.          0.72222222  0.77777778  0.83333333]
 [ 9.22222222  0.94444444  8.77777778  1.05555556  1.11111111]
 [ 1.16666667  2.88888889  2.94444444 25.33333333  1.38888889]]
[[2.83333333e+01 1.11111111e-01 2.94444444e+01 2.25000000e+02
  3.11111111e+01]
 [3.33333333e+00 4.83333333e+01 4.74444444e+02 3.27777778e+01
  7.22222222e+01]
 [8.38888889e+01 3.40000000e+02 7.22222222e+00 7.77777778e+00
  8.33333333e+00]
 [9.22222222e+01 9.44444444e+00 8.77777778e+01 1.05555556e+01
  1.11111111e+01]
 [1.16666667e+01 2.88888889e+01 2.94444444e+01 2.53333333e+02
  1.38888889e+01]]


In [34]:
#Q11
import numpy as np
inv_a = np.linalg.inv(a)       #inverse of a
print("Inverse of a:")
print(inv_a)

print()

inv_b = np.linalg.inv(b)       # inverse of b
print("Inverse of b:")
print(inv_b)


Inverse of a:
[[ 1.37817166e-03 -9.44956586e-04  1.46688218e-04 -6.46850276e-04
   1.30412544e-05]
 [-3.20730359e-03  2.23159197e-03  1.29654005e-03  1.21399238e-03
  -3.56591683e-05]
 [ 3.43945186e-04  9.67915210e-04 -1.30468191e-04 -1.98637727e-04
  -3.21757527e-05]
 [-2.77881865e-04 -3.91211560e-05 -3.13978823e-05  1.36763337e-03
  -1.44151778e-06]
 [-5.05213588e-05 -9.82323300e-05 -3.12925662e-06 -9.83845004e-05
   2.35286480e-04]]

Inverse of b:
[[ 1.37026094e-04 -9.39452432e-05  1.49886094e-05 -6.43856001e-05
   1.29533022e-06]
 [-3.18889364e-04  2.21878261e-04  1.28909790e-04  1.20702405e-04
  -3.54544844e-06]
 [ 3.41970938e-05  9.69288862e-05 -1.29670109e-05 -1.97890457e-05
  -3.21977026e-06]
 [-2.76286820e-05 -4.02309630e-06 -3.20426728e-06  1.36702963e-04
  -1.42378389e-07]
 [-5.02313658e-06 -9.84341026e-06 -3.24648518e-07 -9.84942653e-06
   2.35289705e-05]]


In [42]:
rank_a = np.linalg.matrix_rank(a)     # rank of a
print("Rank of a:", rank_a)

rank_b = np.linalg.matrix_rank(b)     # rank of b
print("Rank of b:", rank_b)


Rank of a: 5
Rank of b: 5


In [43]:
cond_a = np.linalg.cond(a)         # condition number of a
print("Condition number of a:", cond_a)

cond_b = np.linalg.cond(b)         # condition number of b
print("Condition number of b:", cond_b)


Condition number of a: 36.00835138628316
Condition number of b: 35.97444465552643


In [ ]:
u_a, s_a, vt_a = np.linalg.svd(a)         # SVD of a
print("Singular values of a:")
print(s_a)

print()

u_b, s_b, vt_b = np.linalg.svd(b)         # SVD of b
print("Singular values of b:")
print(s_b)

In [44]:
norm_a = np.linalg.norm(a)          # norm of a
print("Norm of a:", norm_a)

norm_b = np.linalg.norm(b)          # norm of b
print("Norm of b:", norm_b)


Norm of a: 1263.288169817164
Norm of b: 12632.866024778383


In [53]:
#Q12
import numpy as np
col_vec = np.array([[22],[14],[27], [38],[50]])

norm_val = np.linalg.norm(col_vec)          # norm(L2) of above col. vector
print("Norm of col. vector:", norm_val)

print()
inner_val = np.dot(col_vec.T, col_vec)       # inner product
print("Inner product:")
print(inner_val)

print()

outer_val = np.dot(col_vec, col_vec.T)        # outer product
print("Outer product:")
print(outer_val)


Norm of col. vector: 73.16419889536138

Inner product:
[[5353]]

Outer product:
[[ 484  308  594  836 1100]
 [ 308  196  378  532  700]
 [ 594  378  729 1026 1350]
 [ 836  532 1026 1444 1900]
 [1100  700 1350 1900 2500]]


In [4]:
#Q13
import numpy as np

def diff_val(func, point, method='central', h=0.01):       # checking which method to use
    if method == 'forward':
        d = (func(point + h) - func(point)) / h

    elif method == 'backward':
        d = (func(point) - func(point - h)) / h

    else:                                                    # central difference (default)
        d = (func(point + h) - func(point - h)) / (2 * h)

    return d

#example check

x0 = 0.5
res1 = diff_val(np.exp, x0)
print("Derivative of e^x at x =", x0, ":", res1)

print()

res2 = diff_val(np.cos, x0)
print("Derivative of cos(x) at x =", x0, ":", res2)


Derivative of e^x at x = 0.5 : 1.648748749525375

Derivative of cos(x) at x = 0.5 : -0.4794175482185081


In [6]:
#Q14

from google.colab import files
import pandas as pd

uploaded = files.upload()                   # csv file upload

# read the uploaded file (use exact filename shown)
df = pd.read_csv("AWS(in).csv")

print(df)


Saving AWS(in).csv to AWS(in).csv
                    created_at  entry_id  Soil Temperature  Soil Moisture  \
0    2022-12-14T14:19:11+05:30     10830             21.06            817   
1    2022-12-14T14:20:13+05:30     10831             21.06            817   
2    2022-12-14T14:21:15+05:30     10832             21.06            817   
3    2022-12-14T14:22:18+05:30     10833             21.06            817   
4    2022-12-14T14:23:20+05:30     10834             21.06            817   
..                         ...       ...               ...            ...   
654  2022-12-26T14:37:18+05:30     11484             20.50            818   
655  2022-12-26T15:17:18+05:30     11485           4095.94            818   
656  2022-12-26T15:57:59+05:30     11486             20.50            818   
657  2022-12-26T16:58:03+05:30     11487             20.00            816   
658  2022-12-26T17:18:03+05:30     11488             19.75            816   

     Wind Speed  Rainfall  Temperature  H